# Generated by Django 5.0.1 on 2024-03-20 04:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_roomsnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại có 10 số và bắt đầu bằng 09 hoặc 03', regex='^(09|03)([0-9]{8})$')])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
