# Generated by Django 5.0.1 on 2024-03-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_price_room_quantity_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='acreage',
            field=models.IntegerField(),
        ),
    ]
