# Generated by Django 5.0.1 on 2024-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_room_roomsnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
