# Generated by Django 5.0.1 on 2024-03-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_guests_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guests',
        ),
    ]
