# Generated by Django 5.0.1 on 2024-03-30 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_electricity'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameHouse', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.house'),
        ),
    ]
