# Generated by Django 5.0.1 on 2024-03-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_house_room_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='id',
        ),
        migrations.AlterField(
            model_name='house',
            name='nameHouse',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
