# Generated by Django 5.0.1 on 2024-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_remove_house_id_alter_house_namehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
