# Generated by Django 5.0.1 on 2024-04-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_alter_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.house'),
        ),
    ]
