# Generated by Django 5.0.1 on 2024-04-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_electricity_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculatator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(default=100)),
                ('wifi_and_trash', models.IntegerField(default=100)),
                ('cleaner', models.IntegerField(default=100)),
                ('use_electricity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.electricity')),
            ],
        ),
    ]
