# Generated by Django 5.0.1 on 2024-04-06 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_calculatator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('fullname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='room.house'),
        ),
        migrations.AddField(
            model_name='house',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to='room.personnel'),
        ),
        migrations.AddField(
            model_name='room',
            name='personnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_personnel', to='room.personnel'),
        ),
    ]
