# Generated by Django 5.0.1 on 2024-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_personnel_alter_room_house_house_personnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
