# Generated by Django 5.0.1 on 2024-04-08 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_alter_guests_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDistrict', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='house',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='roomsNumber',
        ),
        migrations.AddField(
            model_name='electricity',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricity', to='room.room'),
        ),
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_area', to='room.area'),
        ),
        migrations.DeleteModel(
            name='Calculatator',
        ),
    ]
