# Generated by Django 5.0.1 on 2024-04-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_area_remove_electricity_house_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='new_electricity',
            new_name='index_electricity',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='old_electricity',
        ),
    ]
