# Generated by Django 5.0.1 on 2024-04-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_rename_new_electricity_electricity_index_electricity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
