# Generated by Django 5.0.1 on 2024-04-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_guests_date_alter_electricity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='id_personnel',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
