# Generated by Django 5.0.1 on 2024-04-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0022_personnel_id_personnel_alter_personnel_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='personnel',
        ),
    ]
