# Generated by Django 5.0.2 on 2024-04-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0023_remove_room_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='checked_out_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_guests', to='room.room'),
        ),
        migrations.AddField(
            model_name='guests',
            name='status',
            field=models.CharField(default='checked_in', max_length=20),
        ),
    ]
