# Generated by Django 5.0.1 on 2024-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0023_remove_room_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='nameHouse',
            field=models.CharField(max_length=100),
        ),
    ]
