# Generated by Django 5.0.2 on 2024-04-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0024_guests_checked_out_room_guests_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='checked_out_room',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='status',
        ),
    ]
