# Generated by Django 5.0.2 on 2024-04-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0024_house_id_alter_house_namehouse'),
        ('room', '0027_rename_checked_out_room_guests_checkout'),
    ]

    operations = [
    ]
