# Generated by Django 5.0.2 on 2024-04-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0028_merge_20240417_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='status',
        ),
    ]
