# Generated by Django 5.0.2 on 2024-04-17 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0029_remove_guests_checkout_remove_guests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
