# Generated by Django 5.0.1 on 2024-03-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0005_room_price_room_quantity_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_electricity', models.IntegerField()),
                ('new_electricity', models.IntegerField()),
                ('roomsNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
